### ISSUE TITLE
installation fails on yunohost 11

### ISSUE THREAD

**Issue by jbastruz** [YunoHost-Apps/jupyterlab_ynh#111]
hi everyone,

when i try to install Jupyterlab on my yunohost server (version 11.0.9.5), it just fails, and i have the following logs : https://paste.yunohost.org/raw/icusaqosuy

does someone know how to fix this ?

**Comment by ericgaspar** [comment]
Can you try to install from this branch: 
```
sudo yunohost app install https://github.com/YunoHost-Apps/jupyterlab_ynh/tree/yunohost-11
```

**Comment by jbastruz** [comment]
i just tried now and I had another error message : https://paste.yunohost.org/raw/ewaleyayuc

it seems that i have a pre-existing Pipfile

How can i fix that ?

**Comment by ericgaspar** [comment]
I made a mistake. You have tu use the 'fix' branch.
sudo yunohost app install https://github.com/YunoHost-Apps/jupyterlab_ynh/tree/fix

**Comment by jlnbdt** [comment]
Thank you @ericgaspar, I can confirm that it works!

**Comment by jbastruz** [comment]
I confirm too !!!

thanks a lot for your precious and prompt help :)
