### ISSUE TITLE
JupyterLab installation failure

### ISSUE THREAD

**Issue by ebouaziz** [YunoHost-Apps/jupyterlab_ynh#125]
### Describe the bug

JupyterLab installation fails (not an upgrade)

### Context

- Hardware: *i7 PC at home*
- YunoHost version: 11.1.7
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: * yes*
  - Runs in LXC container
- Using, or trying to install package version/branch: 3.5.2~ynh1

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install jupyterlab
    ```

### Expected behavior

*JupyterLab installs*

### Logs

https://paste.yunohost.org/raw/zuvuroqije

There's an issue with pipenv and the parsing of the `--three` argument but I could not find an obvious cause.

**Comment by ebouaziz** [comment]
pipenv removed the deprecated `--three`  switch, this is why it is interpreted as the name of a module to install.

https://github.com/pypa/pipenv/commit/fe99aa13849344a71d090e6d3fca315e77c2ea27

**Comment by ericgaspar** [comment]
Should be fixed with #126
