### ISSUE TITLE
installation failure on Yunohost 3.6.x

### ISSUE THREAD

**Issue by Santosh-Sah** [YunoHost-Apps/jupyterlab_ynh#18]
I have tried many times but it keeps failing from GUI as well as CLI (as shown below)

Is it a public application? [yes | no] (default: yes): 
Enable terminal in the lab? [yes | no] (default: yes): 
Info: Installing application jupyterlab…
Info: [....................] > Validating installation parameters...
Info: [....................] > Storing installation settings...
Info: [....................] > Configuring firewall...
Info: [+++++...............] > Installing dependencies...
Info: Installation of N - Node.js version management
Info: [#####++++++++++++...] > Setting up source files...

It will stuck at this point for very long and then I will loose access to ssh (in case trying from CLI) and GUI will failed to with server not available.

After that I will be doing hard restart (switch off/on power supply) then I could app is installed but on accessing it, it will show 404 nginx error. It doesn't print any logs so dont know which file to check.

Is there a known bug or there is something I m doing it wrongly?

Thank you for porting it to yunohost :)

**Comment by Santosh-Sah** [comment]
Here is the logs from /var/log
https://pastebin.com/BMxseceY

**Comment by kay0u** [comment]
Hi, thank you for your report!

I tried something to fix your (weird) issue, can you please try to install this app in cli with:

```
sudo yunohost app install https://github.com/YunoHost-Apps/jupyterlab_ynh/tree/fix-lock --debug
```

And tell me if it works.

**Comment by Santosh-Sah** [comment]
Hey @kay0u 
Thanks for putting the fix, installation was successful and got the GUI also. But not able to open anything, after clinking I am on getting 403 error.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/9120889/65815993-289b4b00-e214-11e9-838d-f9e770b6600a.png">

**Comment by kay0u** [comment]
Can I get logs of jupyterlab please:

In the admin panel > services > jupyterlab > log > Upload

**Comment by Santosh-Sah** [comment]
Please find the logs as below,

https://paste.yunohost.org/hikivojawi.pl
https://paste.yunohost.org/uvicijelom.http

**Comment by kay0u** [comment]
For what I can see, you are in the folder: `nginx_restart` (in your /home ?), do you have a write access in this folder? Can you try in the ~/ directory please?

**Comment by Santosh-Sah** [comment]
My bad, sorry for my stupidity. You are right, that folder has some scripts which I have written with root so that's why permission was denied.
Currently I am able to create/open ipynb file but interpreter is not working, neither I am able to open terminal.

After clicking on new terminal session, it shows black for few seconds and then just goes back launcher window.
Logs: https://paste.yunohost.org/oyuhoqiyah.http

Screenshot of terminal failure even from shell: 
![image](https://user-images.githubusercontent.com/9120889/65827617-9cd6fc80-e2af-11e9-9171-0317a093c534.png)

**Comment by kay0u** [comment]
You are in a python 3 notebook here, so you have to use python language, not shell ;-)

Try: `print("YunoHost is awesome!")`

This should works as expected.

For the terminal problem, I'm aware of it, but I sadly have no solution for now. /O\ #16.

At least the fix I done works as expected, I'll merge it soon in master :-)

**Comment by Santosh-Sah** [comment]
In actual notebook, shell is integrated.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/9120889/65834058-c8c8a100-e2f4-11e9-8117-b32f40145f94.png">

I think, due to terminal issue, this is happening.

Thank you so much for your time and efforts on this repo.
You can close this issue or else let me know if I can close it.

**Comment by kay0u** [comment]
You're right! It's weird, I don't know how to fix this bug... I have to investigate.

Feel free to contact me if you have any other problems. (Or if you have found a solution for this terminal ;-))

**Comment by Santosh-Sah** [comment]
I was thinking there is something wrong in env variable so I have checked the variable but sadly its good, in fact I am able to run the shell from Ipython from venv

`(jupyterlab) root@pi:/opt/jupyterlab/.venv/bin# ipython
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ls
activate          certipy*           iptest3*     jupyter*                   jupyterhub.sqlite      jupyter-labhub*       jupyter-run*              pip*         python@
activate.csh      chardetect*        ipython*     jupyter-bundlerextension*  jupyter-kernel*        jupyter-migrate*      jupyter-serverextension*  pip3*        python3*
activate.fish     easy_install*      ipython3*    jupyterhub*                jupyter-kernelspec*    jupyter-nbconvert*    jupyter-troubleshoot*     pip3.5*      python3.5@
activate_this.py  easy_install-3.5*  jlpm*        jupyterhub_cookie_secret   jupyter-lab*           jupyter-nbextension*  jupyter-trust*            pygmentize*  python-config*
alembic*          iptest*            jsonschema*  jupyterhub-singleuser*     jupyter-labextension*  jupyter-notebook*     mako-render*              pyjson5*     wheel*

In [2]: print ("hi")
hi

In [3]: pwd
Out[3]: '/opt/jupyterlab/.venv/bin'`

PATH is also fine,
`(jupyterlab) root@pi:/opt/jupyterlab/.venv/bin# echo $PATH
/opt/jupyterlab/.venv/bin:/opt/jupyterlab/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

One more strange thing is **pwd** is working from the notebook,
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/9120889/66057937-252afb00-e557-11e9-9c63-e1424fa77719.png">

Its not the environment issue for sure, so I was thinking to update the **terminado** package to some upper version and test it, what do you say?

Once I get sometime, I will try it.

**Comment by kay0u** [comment]
Your last comment helps me to fix the "ls bug"! You can look at the last PR: #21 
I was doing something wrong with the systemd's conf file.

Though, the terminal still doesn't work.

**Comment by kay0u** [comment]
I just found the problem with the terminal, now everything should work fine!

**Comment by Santosh-Sah** [comment]
> Your last comment helps me to fix the "ls bug"! You can look at the last PR: #21
> I was doing something wrong with the systemd's conf file.
> 
> Though, the terminal still doesn't work.

That's great!
So environment setting was the problem, I had this thoughts to pass additional PATH parameter using shell_command args to test this but good to now from systemd this needs to to done.

**Comment by Santosh-Sah** [comment]
> I just found the problem with the terminal, now everything should work fine!
👍 

You are amazing!
PR link please :)

**Comment by kay0u** [comment]
Everything is on #21:

Env fix: https://github.com/YunoHost-Apps/jupyterlab_ynh/pull/21/commits/a74d60ac15f9c8d93d228f32bfdbaaf7e80390b4

Terminal fix: https://github.com/YunoHost-Apps/jupyterlab_ynh/pull/21/commits/8bb3c404d44e580972dd08c124ffa3b73d275161
