### ISSUE TITLE
JupyterLab Installation failed

### ISSUE THREAD

**Issue by steph2302** [YunoHost-Apps/jupyterlab_ynh#23]
Hi,
I can't install the JupyterLab application in my fresh Yunohost installation.
I don't understand the Warning or why the installation failed.
Maybe the logs can help you ?
[https://paste.yunohost.org/raw/uqojoyiwaz](https://paste.yunohost.org/raw/uqojoyiwaz)

Thank 's

Stephane (french)

**Comment by kay0u** [comment]
Hi, thank you for your report!

For what I can see: 

> RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

```
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```

> Click discovered that you exported a UTF-8 locale but the locale system could not pick up from it because it does not exist.  The exported locale is "fr_FR.UTF-8" but it is not supported.

The problem seems to be your locale... Can you try to use the two commands above and retry the install please?

**Comment by steph2302** [comment]
Thank you for your reply !
It was my Locales. Find a solution there just before you reply : 
[https://www.debian-fr.org/t/resolu-perl-warning-setting-locale-failed/58334/2](https://www.debian-fr.org/t/resolu-perl-warning-setting-locale-failed/58334/2).
So I think it's the same solution.
Install now Ok.

**Comment by kay0u** [comment]
Yeap, same solution. Enjoy JupyterLab and YNH!
