### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by devinberg** [YunoHost-Apps/jupyterlab_ynh#24]
I'm getting an error as I try to upgrade.

https://paste.yunohost.org/raw/yawuqamave

Any help as to how I can fix this?

**Comment by devinberg** [comment]
After a bunch of searching, I was finally able to successfully upgrade by first manually creating the directory `/opt/jupyterlab/config/`

**Comment by kay0u** [comment]
Hi,

Sorry I'm late. Thank your for your report, I'll fix it right now!
