### ISSUE TITLE
Cannot install JupyterLab

### ISSUE THREAD

**Issue by Cornoualis** [YunoHost-Apps/jupyterlab_ynh#28]
Hi,

I try to install JupyterLab but I always have an error:

The full log of my installation attempt can be found here:
https://paste.yunohost.org/wedozagido.bash

Here's the error:
```
2020-02-16 17:23:47,946: DEBUG - /usr/share/yunohost/helpers.d/logging: line 137: pipenv: command not found
```
But pipenv is here:
```
which pipenv
/opt/miniconda3/bin/pipenv
```

I'm sure that the error is due to the fact that I use miniconda...there must be a PATH to add somewhere, but I don't know where.

Thanks in advance for your help!

**Comment by kay0u** [comment]
Hi, and thank you for your report.

I tried to solve this problem, can you install jupyterlab with this command and tell me if it works please?

```
sudo yunohost app install https://github.com/YunoHost-Apps/jupyterlab_ynh/tree/fix-install --force
```

**Comment by Cornoualis** [comment]
Hi and thanks for your help! ;-)

It works...but it doesn't work! The installation works, but when I go to the app, I find a "Jupyter Hub" login page where my Yunohost credentials don't work. My login/password are systematically rejected.
