### ISSUE TITLE
No permission when trying to install pip package

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/jupyterlab_ynh#35]
When I try to install packages with pip to Yunohost JupiterLab venv environment
I get this error:

![image](https://user-images.githubusercontent.com/46165813/78038013-957ed180-736c-11ea-8ccd-8dd24470a954.png)

The folder /opt/jupyterlab/ belongs to root...

`chown -R $USER: /opt/jupyterlab` resolves the permission problem. ($USER=my login name)
Would it make sense to set the permission for the connected user  as default?

**Comment by kay0u** [comment]
This command will probably break the Jupyterlab service, and does not work in a multi-user context.

**Comment by kay0u** [comment]
Did you tried to use the options `--user`?

**Comment by ericgaspar** [comment]
> Did you tried to use the options `--user`?

Yes I did but with no success.

In the install script, permission is set to root for `/opt/jupyterlab` and to admin for `/opt/jupyterlab/.venv/share`

I can't figure out how to connect to jupyterlab with admin.


```
#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
chown -R root: $final_path
chown -R $admin: $final_path/.venv/share
```

**Comment by ericgaspar** [comment]
I can't see jupyterLab group in `/etc/group`.
Will it make sense to creat a group user to JupyterLab and assign the access rights to the venv folder to this goup?
`chown -R $app: $final_path/.venv/share`
