### ISSUE TITLE
502 Bad Gateway after new install

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/jupyterlab_ynh#37]
I get a 502 Bad Gateway  error after a fresh install as well as update from the testing branch.
[Installation logs](https://paste.yunohost.org/raw/aqekovagog)
I have deleted the app and reinstalled from master branch and I get the same error.

**Comment by kay0u** [comment]
Can I have logs from the service please? (https://domain.tld/yunohost/admin/#/services/jupyterlab/)

**Comment by ericgaspar** [comment]
Logs from the service:
https://paste.yunohost.org/zovunawazu

**Comment by kay0u** [comment]
I found the issue, I made a mistake when I updated the config file, fixed here: https://github.com/YunoHost-Apps/jupyterlab_ynh/pull/38

I'm sorry for that, you can force the upgrade with:

```
sudo yunohost app upgrade jupyterlab -u https://github.com/YunoHost-Apps/jupyterlab_ynh
```

Or wait the app list rebuild (8h maximum)

**Comment by ericgaspar** [comment]
Thanks! it works
