### ISSUE TITLE
No kernel available

### ISSUE THREAD

**Issue by HadrienLG** [YunoHost-Apps/jupyterlab_ynh#39]
Version : 2.1.0~ynh2
JupyterLab installed without problem, I can log to JupyterLab (with my username in lowercase?!)
But I can't start a kernel (python 3), it remains stuck at "Kernel Initializing" when I execute a cell in my notebook. The cell indicate [*] but is not computing.

**Comment by kay0u** [comment]
Hi, and thank you for your report.

Can you try the new version please?

If it doesn't work, can you please give me some logs (via the webadmin or in cli: `sudo journalctl -u jupyterlab`)?

**Comment by HadrienLG** [comment]
New version installed, it works!
Thank you for your time
