### ISSUE TITLE
Not able install extensions (requirex nodjejs >= 10)

### ISSUE THREAD

**Issue by sant-sh** [YunoHost-Apps/jupyterlab_ynh#45]
I am not sure if extensions are supported, if it is then I think nodejs package needs to be updated as I am getting below error,

![image](https://user-images.githubusercontent.com/9120889/80421792-a6cee580-88fa-11ea-9755-854c077c02b0.png)

**Comment by ericgaspar** [comment]
@sant-sh You can try to install the testing version, it updates nodejs to v.10 

`sudo yunohost app upgrade jupyterlab -u https://github.com/YunoHost-Apps/jupyterlab_ynh/tree/testing`

**Comment by sant-sh** [comment]
@ericgaspar it worked!
Will it be merged to main branch?

**Comment by ericgaspar** [comment]
It will, in a few days I guess.
