### ISSUE TITLE
installation not visible in user interface

### ISSUE THREAD

**Issue by arnoudspammer** [YunoHost-Apps/jupyterlab_ynh#9]
installation doesn't make a label in user interface and I have no idea how I can access the service on my server

**Comment by kay0u** [comment]
Hi!

Are you sure the application is installed correctly? Because the installation creates a label in the user interface if the installation was successful. Can you give me your logs please? You can retrieved it here:

`Admin panel->Tools-> Logs-> Install 'Jupyterlab' application.`

**Comment by arnoudspammer** [comment]
Hi, 

It seems it doesn't install correctly indeed. my connection with my ssh was severed after 45 minutes or so installing (?!). I had made an additional /jupyterlab on my main domain. I don't know if that breaks things. https://paste.yunohost.org/raw/qekuvupumi is my log.

**Comment by kay0u** [comment]
Your log is not full, or the install suddenly stopped (probably due to your ssh problem).

Please try:

```
sudo yunohost app remove jupyterlab
```
(This command may fail if jupyterlab is not consider has installed)

And then reinstall (maybe with the admin panel to be sure it not happen again?).

Tell me if you have another problem

**Comment by arnoudspammer** [comment]
I will try. half hour later. seems that everything works :)
