### ISSUE TITLE
How to install python modules

### ISSUE THREAD

**Issue by h3ndrik** [YunoHost-Apps/jupyterlab_ynh#94]
I'd like to use `matplotlib` on my instance. But i'm not really sure what i'm expected to do. I saw this app uses a venv somewhere. But i'm not sure if users should install packages (per kernel?) themselves or if this is done by the admin (and how).

Also I'd like to avoid managing and updating too many seperate environments. Can i just install my favorite python modules system-wide and debian does the updates? I tried `apt install python3-matplotlib` but that isn't available inside the jupyterlab venv.

(Jupyterlab 3.0.16 // YunoHost 4.2.6.1)

**Comment by ericgaspar** [comment]
`pip install matplotlib`should work.

**Comment by ericgaspar** [comment]
This is how it should work with the testing version (#93), with the option to allow users to install extensions:
https://github.com/YunoHost-Apps/jupyterlab_ynh/blob/3fb76af25d0bc1717aa07ef1e5dd3825ca23f058/manifest.json#L64-L70
But right now there is still some issues to solve before merging to master.

**Comment by h3ndrik** [comment]
thank you for the clarification
